---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant2helmrelease3
  namespace: tenant1
spec:
  chart:
    spec:
      chart: ./tenant1app
      interval: 1m0s
      sourceRef:
        kind: GitRepository
        name: tenant2helmrepo2
        namespace: tenant1
      version: 1.0.0
  install:
    remediation:
      retries: 3
  interval: 5m0s
  releaseName: tenant2helmrelease3
  targetNamespace: tenant1
  timeout: 2m0s
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: "1.19"
    nameOverride: ""
    fullnameOverride: ""
    replicaCount: 1
    serviceAccount: 
      create: true 
      annotations: {} 
      name: ""
    service:
      type: ClusterIP
      port: 80
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tenant2helmrepo2
  namespace: tenant1
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/fk-gitops/helm-repo
